# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
email: me@robdmoore.id.au
url: https://robdmoore.id.au
title: Robert Daniel Moore's Blog
name: Robert Daniel Moore's Blog
description: 'Blog about software engineering, web development, agile/lean/Continuous Delivery, C#, ASP.NET and Microsoft Azure.'
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: robdmoore
github_username:  robdmoore
permalink: /blog/:year/:month/:day/:title

# Build settings
excerpt_separator: "<!--more-->"
markdown: kramdown
theme: jekyll-theme-basically-basic
plugins:
  - jekyll-feed
